### ISSUE TITLE
Deploy in namespace without using a ClusterRole

### ISSUE THREAD

**Issue by gjcarneiro** [nats-io/nats-operator#102]
I want nats operator to be fully self-contained in a namespace, without requiring cluster level permissions.  To that end I modified the yamls to use Role instead of ClusterRole.  But I get this error from nats operator:

```
time="2018-11-30T18:40:50Z" level=error msg="initialization failed: fail to create CRD: customresourcedefinitions.apiextensions.k8s.io is forbidden: User \"system:serviceaccount:molly-dev:nats-operator\" cannot create resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope" pkg=controller
```

Why does nats-operator need to create customresourcedefinitions?

I've been googling for the issue, and the closes I can find that is relevant is the etcd-operator: https://github.com/coreos/etcd-operator/blob/master/doc/user/rbac.md#role-vs-clusterrole

```
--create-crd=false Creates a CR without first creating a CRD.
In this mode the operator can be run with just a Role without the permission to create a CRD.
```

Maybe nats operator needs a similar option?

Here's my full yaml file:

```yaml

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nats-operator
rules:
# Allow creating CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
# Allow all actions on NatsClusters
- apiGroups:
  - nats.io
  resources:
  - natsclusters
  - natsserviceroles
  verbs: ["*"]
# Allow actions on basic Kubernetes objects
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  verbs: ["*"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-operator

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nats-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nats-operator
subjects:
- kind: ServiceAccount
  name: nats-operator

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsclusters.nats.io
spec:
  group: nats.io
  names:
    kind: NatsCluster
    listKind: NatsClusterList
    plural: natsclusters
    singular: natscluster
    shortNames:
    - nats
  scope: Namespaced
  version: v1alpha2

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsserviceroles.nats.io
spec:
  group: nats.io
  names:
    kind: NatsServiceRole
    listKind: NatsServiceRoleList
    plural: natsserviceroles
    singular: natsservicerole
  scope: Namespaced
  version: v1alpha2

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nats-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-operator
  template:
    metadata:
      labels:
        name: nats-operator
    spec:
      serviceAccountName: nats-operator
      containers:
      - name: nats-operator
        image: connecteverything/nats-operator:0.3.0-v1alpha2
        imagePullPolicy: Always
        ports:
        - name: readyz
          containerPort: 8080
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /readyz
            port: readyz
          initialDelaySeconds: 15
          timeoutSeconds: 3
```
