### ISSUE TITLE
Deploy as DaemonSet so that a Nats Client Runs on Each Node

### ISSUE THREAD

**Issue by sibblegp** [nats-io/nats-operator#113]
Is there a way to deploy the operator as a daemon set or using Anti Affinity so that you can place each server one or two to a node so that clients will connect to the node running on their machine? Thanks!

**Comment by wallyqs** [comment]
@sibblegp yes this should be possible by setting `antiAffinity: true` as part of the configuration
```yaml
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats"
spec:
  size: 3
  version: "1.3.0"
  pod:
    antiAffinity: true
```
