### ISSUE TITLE
can't set NatsCluster pods to specific nodes

### ISSUE THREAD

**Issue by phynias** [nats-io/nats-operator#114]
I am trying to have all the nats related pods on particular nodes. I have everything but the NatsCluster pods working

```
---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "my-nats"
spec:
  size: 3
  template:
    spec:
      nodeSelector:
        my.pool: nats

```
I have the nodeselector in place for NatsStreamingCluster and it works.
But for NatsCluster, it puts the pods randomly on different nodes.
