### ISSUE TITLE
Exposing the NATS server with an External IP

### ISSUE THREAD

**Issue by Ravenwater** [nats-io/nats-operator#120]
In my use case, subscribers can come from outside the K8s cluster, and thus I need an external IP for the messaging port. What would be the right design to accomplish this in the chart as a configurable parameter?

**Comment by nerijus** [comment]
Just FYI, the following LoadBalancer on DigitalOcean works:
```
---
kind: Service
apiVersion: v1
metadata:
  name: tcp-lb
spec:
  type: LoadBalancer
  selector:
    app: nats
  ports:
    - name: nats
      protocol: TCP
      port: 4222
      targetPort: 4222
```
You can use:
```
  selector:
    nats_cluster: nats-cluster
```
as well.
