### ISSUE TITLE
Authentication with serviceaccounts doesn't work

### ISSUE THREAD

**Issue by Smana** [nats-io/nats-operator#129]
Hey guys,

I'm currently testing the nats operator and I would like to use the serviceaccounts to manage the permissions as stated in the documentation.
We're using the kubernetes version 1.13.2 so the token request API is already enabled.

I deployed the nats-operator using the helm chart, pretty straightforward. I just changed 2 values as follows:
```
image:
  tag: 0.4.0-v1alpha2
auth:
  enableServiceAccounts: true
```

Then I wanted to test the permissions using natsserviceroles and the example from the documentation:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin-user
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-user
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-user
  namespace: default

  # Specifies which NATS cluster will be mapping this account.
  labels:
    nats_cluster: nats-cluster
spec:
  permissions:
    publish: ["foo.*", "foo.bar.quux"]
    subscribe: ["foo.bar"]
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-admin-user
  namespace: default
  labels:
    nats_cluster: nats-cluster
spec:
  permissions:
    publish: [">"]
    subscribe: [">"]
```
```
kubectl apply -f natservicerole.yaml 
serviceaccount/nats-admin-user created
serviceaccount/nats-user created
natsservicerole.nats.io/nats-user created
natsservicerole.nats.io/nats-admin-user created
```

And I created the test pod (using the newly created secret):
```
kubectl get secret | grep nats-user  
nats-user-token-44q4f                   kubernetes.io/service-account-token   3      114s
```
```
apiVersion: v1
kind: Pod
metadata:
  name: nats-user-pod
  labels:
    nats_cluster: nats-cluster
spec:
  volumes:
    - name: "token"
      projected:
        sources:
        - secret:
            name: "nats-user-token-44q4f"
            items:
              - key: token
                path: "token"
  restartPolicy: Never
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "wallyqs/nats-ops:latest"
      tty: true
      stdin: true
      stdinOnce: true
      volumeMounts:
      - name: "token"
        mountPath: "/var/run/secrets/nats.io"
```
```
/go # nats-sub -s nats://nats-user:`cat /var/run/secrets/nats.io/token`@nats-cluster:4222 foo.bar
Listening on [foo.bar]
```
However using another user works too ....
```
/go # nats-sub -s nats://nats-admin-user:`cat /var/run/secrets/nats.io/token`@nats-cluster:4222 foo.bar
Listening on [foo.bar]
```
I had a look to the nats.conf secret and nothing seems changed, we still have the same default config:
```
kubectl get secret nats-cluster -o yaml
echo "<b64>" | base64 -d
{
  "port": 4222,
  "http_port": 8222,
  "cluster": {
    "port": 6222,
    "routes": [
      "nats://nats-cluster-1.nats-cluster-mgmt.default.svc:6222",
      "nats://nats-cluster-2.nats-cluster-mgmt.default.svc:6222",
      "nats://nats-cluster-3.nats-cluster-mgmt.default.svc:6222"
    ]
  },
  "authorization": {}
}
```
