### ISSUE TITLE
Custom Server Configuration does not work. natsConfig is not applied to the secret.

### ISSUE THREAD

**Issue by benjsicam** [nats-io/nats-operator#135]
Custom Server Configuration does not work. natsConfig is not applied to the secret.

```
---
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-cluster
spec:
  size: 3
  version: "1.4.1"
  natsConfig:
    max_connections: 150
    max_payload: 2097152
```

When I get the secret details, the custom configuration isn't applied on the actual content of nats.conf.
