### ISSUE TITLE
How to expose nats server  with an external IP with advertiseExternalIP option

### ISSUE THREAD

**Issue by nithinkd-geon** [nats-io/nats-operator#152]
hello
how to expose  nats cluster to external IP with advertiseExternalIP option i just tried below settings and it is not worked

used : AKS cluster

created an LB with appropriate selector and port opened for 4222

and configured nats-cluster with below settings

```yaml
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: demo-nats-cluster
spec:
  size: 2
  version: "1.4.1"
  tls:
    serverSecret: "nats-clients-tls"
    routesSecret: "nats-routes-tls"
  pod:
    enableClientsHostPort: true
    advertiseExternalIP: true
    bootconfigImage: "connecteverything/nats-boot-config"
    bootconfigImageTag: "0.5.0"
  template:
    spec:
      serviceAccountName: "nats-server"
```

but  i am getting  the error from init controller 

```
time="2019-03-26T03:04:46Z" level=info msg="Starting NATS Server boot config v0.5.0"
time="2019-03-26T03:04:46Z" level=info msg="Pod running on node \"aks-nodepool1-36780942-0\""
time="2019-03-26T03:04:46Z" level=fatal msg="Could not find external IP address."
```

FYI . i am able to expose nats cluster without these by  just adding the LB alone(with out init pod) ,but i am not sure whether that is an right approach

please clarify & how to expose nats cluster to outside clients
