### ISSUE TITLE
ServerConfig change should trigger UpdateConfigSecret?

### ISSUE THREAD

**Issue by schancel** [nats-io/nats-operator#160]
Hey @wallyqs,

When the server config is updated, (e.g.: MaxCOnnections, etc.)  what triggers `UpdateConfigSecret` to be called?

I don't see any code anywhere.  I was looking due to the discussion on https://github.com/nats-io/nats-operator/pull/159.

It seems like tracking the file-path should be unnecessary as a deep-equal on the NatsCluster should cause the config secret to be updated.  However, I can't find that happening anywhere.

**Comment by wallyqs** [comment]
There is a function named `Reconcile` that is called whenever the `NatsCluster` CRD object changes here:

https://github.com/nats-io/nats-operator/blob/6ea69320a9604ab8fd1c52bbd39df085b9e8afcd/pkg/controller/controller.go#L213

When `Reconcile` is called, it also calls `updateCluster` → `UpdateConfigSecret`:

https://github.com/nats-io/nats-operator/blob/6ea69320a9604ab8fd1c52bbd39df085b9e8afcd/pkg/cluster/cluster.go#L168-L172

Then in case there were any changes, the config secret is applied the changes:

https://github.com/nats-io/nats-operator/blob/803f2599f70c6b6e9a046ce52a1d26af59ebec94/pkg/cluster/cluster.go#L474-L481

This causes K8S to remount file with the updated secret which can take time occasionally (but usually less than a minute from what I have seen).  On Kubernetes v1.12, a reloader sidecar can be attached to the NATS Server so that as soon as the volume is remounted with the new configuration, it signals HUP to the server so that it reloads the configuration once again.  For example, with the following manifest, toggling the debug/trace flag and applying `kubectl` multiple times would disable/enable verbose logging:

```yaml
---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-custom"
spec:
  size: 3
  version: "1.4.1"

  pod:
    enableConfigReload: true

  natsConfig:
    debug: true
    trace: true
    maxPayload: 5242880 # 5MB
```
