### ISSUE TITLE
RBAC support

### ISSUE THREAD

**Issue by valichek** [nats-io/nats-operator#17]
Currently it is not possible to run provided resources when RBAC is enabled.

**Comment by wallyqs** [comment]
This worked for me to deploy the operator in clusters with RBAC enabled

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-operator
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: nats-operator
rules:

- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - create

- apiGroups:
  - nats.io
  resources:
  - natsclusters
  verbs:
  - "*"

- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["*"]

- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  verbs: ["*"]

- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  verbs: ["*"]

- apiGroups: [""]
  resources:
  - services
  - endpoints
  verbs: ["get", "create", "update"]

- apiGroups: [""]
  resources:
  - nodes
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: nats-operator

subjects:
- kind: ServiceAccount
  name: nats-operator
  namespace: default

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
```
