### ISSUE TITLE
Feature request: Prometheus ServiceMonitor

### ISSUE THREAD

**Issue by Starefossen** [nats-io/nats-operator#176]
The classic way of monitoring pods with Prometheus is with scrape annotations. The Prometheus Operator which is becoming more and more popular way of deploying Prometheus has moved away from annotations to a custom object called a [`ServiceMonitor`][servicemonitor].

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-apps-http
  labels:
    k8s-apps: http
spec:
  jobLabel: k8s-app
  selector:
    matchExpressions:
    - {key: k8s-app, operator: Exists}
  namespaceSelector:
    matchNames:
    - kube-system
    - monitoring
  endpoints:
  - port: http-metrics
    interval: 15s
```

The order in which the Pods, Services, and ServiceMonitor is created is not important.

[servicemonitor]: https://github.com/coreos/prometheus-operator/blob/master/Documentation/user-guides/running-exporters.md
