### ISSUE TITLE
Run nats pods as non root 

### ISSUE THREAD

**Issue by Gizmos777** [nats-io/nats-operator#196]
Hello.
We have a Pod Security Policy in the kubernetes cluster. It prohibits run as root.
I created NatsCLuster:

```
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: test-nats
  namespace: default
spec:
  securityContext:
    runAsUser: 1001
  size: 3
  version: 1.4.1
```

But nats pod didn't start due to error:
  
`Error: container has runAsNonRoot and image will run as root`

How can i configure nats to run as non root?
