### ISSUE TITLE
how to access nats from k8s setup

### ISSUE THREAD

**Issue by vkuznet** [nats-io/nats-operator#220]
Hi,
I followed all [readme](https://github.com/nats-io/nats-operator/blob/master/README.md) instructions and I can see that my nats server is running, e.g.
```
kubectl get nats
NAME           AGE
nats-cluster   1h
kubectl get svc
NAME                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
kubernetes          ClusterIP   10.254.0.1       <none>        443/TCP                      95m
nats-cluster        ClusterIP   10.254.220.136   <none>        4222/TCP                     76m
nats-cluster-mgmt   ClusterIP   None             <none>        6222/TCP,8222/TCP,7777/TCP   76m
```

But I can't access it from nats clients, e.g. (here I use `myhost.server.com` as an example):
```
nats-sub -s nats://myhost.server.com:4222 test
nats: no servers available for connection
```
but I can see my `myhost.server.com`

If I add `nginx` controller with http end-point I can curl to nats server, e.g.
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-nats
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: myhost.server.com
    http:
      paths:
      - path: /
        backend:
          serviceName: nats-cluster
          servicePort: 4222
```
then I can use curl command
```
curl http://myhost.server.com/
INFO {"server_id":"2V7gpl6VhHhFsHHY7mdlQ2","version":"1.3.0","proto":1,"git_commit":"eed4fbc","go":"go1.11","host":"0.0.0.0","port":4222,"max_payload":1048576,"client_id":6,"connect_urls":["10.100.1.15:4222","10.100.2.6:4222"]}
-ERR 'Unknown Protocol Operation'
```
So, it seems to be working, but I can't see how my nats client can connect to it.

What am I missing in nats k8s setup?

**Comment by wallyqs** [comment]
Hi, instead of using an ingress you would have to expose the cluster via a host port and also make it possible to advertise its public ip.  You can do that with the example below:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-server
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-server
rules:
- apiGroups: [""]
  resources:
  - nodes
  verbs: ["get"]
---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "nats-cluster"
spec:
  size: 3
  version: "2.1.0"

  pod:
    enableClientsHostPort: true
    advertiseExternalIP: true

  template:
    spec:
      serviceAccountName: "nats-server"
```
