### ISSUE TITLE
Resources requests/limits for NATS cluster CRD

### ISSUE THREAD

**Issue by CarpathianUA** [nats-io/nats-operator#236]
Hi guys!
Is there any possibility to set a container resources (req/lim) for NATS cluster?

**Comment by Miouge1** [comment]
I'm looking for that option as well. Is there anything possible with the `spec.podTemplate` key?

**Comment by egoon** [comment]
You can use podPolicy `spec.pod` to set the container resource limits.

```
spec:
  pod:
    resources:
      limits:
        cpu: "200m"
        memory: "500Mi"
      requests:
        cpu: "100m"
        memory: "100Mi"
```
