### ISSUE TITLE
NatsCluster doesn't update pods with new limits and requests configurations

### ISSUE THREAD

**Issue by mfaur** [nats-io/nats-operator#249]
I have recently added limits and requests to my NatsCluster resource as follows:
```
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats-cluster
spec:
  size: 2
  pod:
    resources:
      requests:
        memory: "300Mi"
        cpu: 200m
      limits:
        memory: "600Mi"
        cpu: 400
```
When applying the changes the NatsCluster resource was updated but the pods it was running weren't. Only after manually deleting the pods did the NatsCluster create new pods with the new configurations.
