### ISSUE TITLE
Specify Image for Cluster

### ISSUE THREAD

**Issue by jselleck** [nats-io/nats-operator#261]
Is it possible to set the image on a NATS cluster to accommodate locations that may not have direct docker.io access.  Not being able to is preventing me from using the operator on several of our networks.  Thanks!

For example - something like:
```
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: dso-nats-cluster
spec:
  size: 3
  version: "2.1.4"
  image: myreg.custom.com:5555/nats:2.1.4
```
