### ISSUE TITLE
ServiceAccount authentication from different namespace failed

### ISSUE THREAD

**Issue by Da5-Id** [nats-io/nats-operator#263]
How does ServiceAccount authentication work for the given deployment:

- Deploy nats-cluster in a custom namespace e.g. "infrastructure" 
- Deploy ServieAccount (nats-admin-user) for the cluster namespace "infrastructure" and the client namespace "app"

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin-user
  namespace: infrastructure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-admin-user
  namespace: app
---
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  name: nats-admin-user
  namespace: infrastructure
  labels:
    nats_cluster: nats
spec:
  permissions:
    publish: [">"]
    subscribe: [">"]
```

- The operator creates secrets with token for the defined ServiceAccounts in each namespace ( "nats-admin-user-nats-bound-token")
- Deploy the sample pod "nats-ops" in the "app" namespace and mount the token from the secret "nats-admin-user-nats-bound-token"

```
apiVersion: v1
kind: Pod
metadata:
  name: nats-admin-user-pod
  namespace: app
  labels:
    nats_cluster: nats
spec:
  volumes:
    - name: token
      projected:
        sources:
          - secret:
              name: "nats-admin-user-nats-bound-token"
              items:
                - key: token
                  path: "token"
  restartPolicy: Never
  serviceAccountName: nats-admin-user
  containers:
    - name: nats-ops
      command: ["/bin/sh"]
      image: "wallyqs/nats-ops:latest"
      tty: true
      stdin: true
      stdinOnce: true
    # Service Account Token is mounted via projected volume.
      volumeMounts:
      - name: token
        mountPath: "/var/run/secrets/nats.io"
        readOnly: true

```
`/go # nats-sub -s nats://nats-admin-user:'cat /var/run/secrets/nats.io/token'@nats.infrastructure:4222 hello.world`

When attaching to the "nats-ops" - pod and connecting to the nats cluster a "authorization violation" occures. 

When changing the token with the token of the secret "nats-admin-user-nats-bound-token" in the namespace "infrastructure" the connection will work.

While we cannot mount a secret that is defined in a diffenrent namespace ("infrastructure") in a container in the namespace "app", how does the ServiceAccount authentication work for a nats cluster and a client pod in different namespaces ?

Thanks

Additional Informations:

I am using the recent operator and reloader from the sources (build the dockerfiles in kubernetes locally).

The problem seems to be the identification of the ServiceAccount when a there are at least two ServiceAccounts with the same name in different namespaces. When changing the ServiceAccount names so that each ServiceAccount name is unique then the authentication will work.
