### ISSUE TITLE
Support leafnode remotes

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats-operator#268]
Need a similar configuration block like the helm charts

```yaml
leafnodes:
  enabled: true
  remotes:
    - url: tls://connect.ngs.global:7422
      credentials:
        secret:
          name: ngs-creds
          key: NGS.creds
```
