### ISSUE TITLE
Set Resources requests/limits default limits

### ISSUE THREAD

**Issue by NissesSenap** [nats-io/nats-operator#270]
Hey

As a happy beginner with nats it would be nice to get some decent default resources request/limits with the operator.
I know that I can put them down myself as defined in #236 

I know setting defaults limits is hard due to that you don't know what kind of workload you want to run on nats but I personally think something small is better then nothing.

**Comment by jorgelon** [comment]
try with this in the helm chart

```yaml
container:
  merge:
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 50Mi
```
