### ISSUE TITLE
Allow overriding of service name via values.yaml

### ISSUE THREAD

**Issue by IAXES** [nats-io/nats-operator#273]
Can we modify the name of the service object so that it can be customized via `values.yaml`? i.e. change it from this:

```yaml
 {{- default .Release.Name -}}
```

To something like so:

```yaml
 {{- default .Release.Name .Values.nameOverride | trunc 63 | trimSuffix "-" | trimSuffix "." -}}
```

I have a top-level chart that pulls in nats-operator alongside other charts, and there are cases where a top-level chart has two third-party sub-charts that use `{{- default .Release.Name -}}` for the name of a service object (resulting in a naming collision). It'd be great to be able to override this outright.

**Comment by wallyqs** [comment]
We've gotten similar requests in other Helm chart like this so I think sounds good to adopt nameOverride here as well
https://github.com/nats-io/k8s/commit/c43203fe9b5fb5f6c59b335188c6832a0b033b6e

**Comment by IAXES** [comment]
That's almost exactly the patch I would have proposed (if I had to write it from scratch). It's to my understanding that `.Release.Name` and templated values (i.e. from `_helpers.tpl`) in sub-charts cannot be overriden via the parent chart, so it's either this type of change, or forking the chart.

**Comment by IAXES** [comment]
While we're at it, can we extend this feature to the `nats-box` helper-pod?

**Comment by IAXES** [comment]
@wallyqs I'm happy to provide the PR/patch, if it helps with lead time. Do you have a docker container or test/regression script I should test my patched chart against prior to putting up the code review?

**Comment by wallyqs** [comment]
Thanks @IAXES this is a small fix so I can take a look at it today.

**Comment by wallyqs** [comment]
A bit confused, it seems that the helm chart here already supports `nameOverride`: https://github.com/nats-io/nats-operator/blob/master/helm/nats-operator/templates/_helpers.tpl#L7
Maybe this is a duplicate of https://github.com/nats-io/k8s/pull/62?

**Comment by IAXES** [comment]
Here's the repo setup I have:

```sh
nats                    https://nats-io.github.io/k8s/helm/charts/
```

Inspecting the output of `helm fetch nats/nats` (output is in `nats-0.4.0.tgz`):

**`nats/templates/service.yaml`**
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "nats.name" . }}
  labels:
    app: {{ template "nats.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app: {{ template "nats.name" . }}
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitor
    port: 8222
  - name: metrics
    port: 7777
  - name: leafnodes
    port: 7422
  - name: gateways
    port: 7522
```

From **``nats/templates/_helpers.tpl**
```
 1 {{/*
 2 Expand the name of the chart.
 3 */}}
 4 {{- define "nats.name" -}}
 5 {{- default .Release.Name -}}
 6 {{- end -}}
```

So, assuming I'm pulling the latest-and-greatest helm release of NATS-operator correctly, the K8S service object doesn't support the features exposed by the above-noted patch.
