### ISSUE TITLE
nats-cluster pod Init:CrashLoopBackoff

### ISSUE THREAD

**Issue by Olli64** [nats-io/nats-operator#275]
Greetings!

I've recently upgraded my AKS Cluster(to 1.16.9) and after that the nats cluster pod is in state Init:CrashLoopBackOff.

I've installed the operator following your guide.

nats-cluster.yaml
```
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: platta-nats-cluster
spec:
  size: 2
  version: "1.3.0"

  pod:
    enableConfigReload: true
    enableClientsHostPort: true
    advertiseExternalIP: true
```

nats-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-operator
  # Change to the name of the namespace where to install NATS Operator.
  # Alternatively, change to "nats-io" to perform a cluster-scoped deployment in supported versions.
  namespace: nats-io
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-operator
  template:
    metadata:
      labels:
        name: nats-operator
    spec:
      serviceAccountName: nats-operator
      containers:
      - name: nats-operator
        image: connecteverything/nats-operator:0.7.2
        imagePullPolicy: IfNotPresent
        args:
        - nats-operator
        # Uncomment to perform a cluster-scoped deployment in supported versions.
        - --feature-gates=ClusterScoped=true
        ports:
        - name: readyz
          containerPort: 8080
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        readinessProbe:
          httpGet:
            path: /readyz
            port: readyz
          initialDelaySeconds: 15
          timeoutSeconds: 3
```

Operator is running with no events.

Latest events from default namespace:
```
47m         Warning   BackOff                  pod/platta-nats-cluster-1            Back-off restarting failed container
<unknown>   Normal    Scheduled                pod/platta-nats-cluster-1            Successfully assigned default/platta-nats-cluster-1 to aks-nodepool1-87507524-vmss000002
41m         Normal    Pulled                   pod/platta-nats-cluster-1            Container image "connecteverything/nats-boot-config:0.5.2" already present on machine
41m         Normal    Created                  pod/platta-nats-cluster-1            Created container bootconfig
41m         Normal    Started                  pod/platta-nats-cluster-1            Started container bootconfig
12m         Warning   BackOff                  pod/platta-nats-cluster-1            Back-off restarting failed container
<unknown>   Normal    Scheduled                pod/platta-nats-cluster-1            Successfully assigned default/platta-nats-cluster-1 to aks-nodepool1-87507524-vmss000000
5m10s       Normal    Pulled                   pod/platta-nats-cluster-1            Container image "connecteverything/nats-boot-config:0.5.2" already present on machine
5m10s       Normal    Created                  pod/platta-nats-cluster-1            Created container bootconfig
5m10s       Normal    Started                  pod/platta-nats-cluster-1            Started container bootconfig
89s         Warning   BackOff                  pod/platta-nats-cluster-1            Back-off restarting failed container
43m         Warning   FailedToUpdateEndpoint   endpoints/platta-nats-cluster-mgmt   Failed to update endpoint default/platta-nats-cluster-mgmt: Operation cannot be fulfilled on endpoints "platta-nats-cluster-mgmt": StorageError: invalid object, Code: 4, Key: /registry/services/endpoints/default/platta-nats-cluster-mgmt, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 1d9deebd-e17a-4aa8-886e-26fbd68aac14, UID in object meta:
43m         Warning   FailedToUpdateEndpoint   endpoints/platta-nats-cluster        Failed to update endpoint default/platta-nats-cluster: Operation cannot be fulfilled on endpoints "platta-nats-cluster": StorageError: invalid object, Code: 4, Key: /registry/services/endpoints/default/platta-nats-cluster, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 8c825e0f-3f0b-4dc8-9d9d-6e9457943ee5, UID in object meta:
```
latest log lines from operator pod from namespace nats-io:
```
ime="2020-07-14T08:30:08Z" level=info msg="skipping reconciliation as there are 1 waiting pods ([platta-nats-cluster-1])" cluster-name=platta-nats-cluster namespace=default pkg=cluster
```

I have no idea what you guys need to solve out some problems so please let me know what I can provide you :)
