### ISSUE TITLE
example nats-operator-cluster-scoped is missing serviceaccount

### ISSUE THREAD

**Issue by sanderma** [nats-io/nats-operator#276]
When deploying the example `nats-operator-cluster-scoped.yaml` the replicaset shows the error: `Error creating: pods "nats-operator-7b44c857bb-" is forbidden: error looking up service account nats-io/nats-operator: serviceaccount "nats-operator" not found`.

The serviceaccount is indeed not present in the example.

After adding the serviceaccount the deploy succeeds:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-operator
  namespace: nats-io
```
