### ISSUE TITLE
Nats-Pod crashes when deploying nats cluster with super cluster / gateway configuration

### ISSUE THREAD

**Issue by Da5-Id** [nats-io/nats-operator#279]
I try to deploy one nats cluster with a gateway configuration to build a super cluster.

The yaml looks like this:

```
apiVersion: nats.io/v1alpha2
kind: NatsCluster
metadata:
  name: nats
  namespace: nats
spec:
  size: 3
  version: "2.1.7"
  noAdvertise: true
  
  pod:
    enableConfigReload: true
    reloaderImage: connecteverything/nats-server-config-reloader
    reloaderImageTag: "0.6.0"
    reloaderImagePullPolicy: "IfNotPresent"

  auth:
    enableServiceAccounts: true    

  gatewayConfig:
	name: "nats-one-gw"
	hostPort: 7522
	rejectUnknown: true

  gateways:
    - name: nats-two-gw
      url: "nats://nats-two:7522"
template:
  spec:
    containers:
     - name: nats
```

The pod crashes with this error message:

_nats-server: error parsing include file 'advertise/gateway_advertise.conf', open /etc/nats-config/advertise/gateway_advertise.conf: no such file or directory_

The nats config ( kubernetes secret ) contains an include

` include  "advertise/gateway_advertise.conf",
  "gateway": {
    "name": "nats-one-gw",
    "port": 7522,
    "gateways": [
      {
        "name": "nats-two-gw",
        "url": "nats://nats-two:7522"
      }
    ],
    "reject_unknown": true`

While advertising is disabled I wonder why there is an include to _advertise/gateway_advertise.config_ ?
Who is responsible to create the gateway_advertise.config ?
