### ISSUE TITLE
NATS cluster bound tokens randomly being deleted

### ISSUE THREAD

**Issue by akubala** [nats-io/nats-operator#310]
Hello!

I am using the following setup on Kubernetes v1.18.9 (EKS):

**nats-operator**
- image: `natsio/nats-operator:0.8.2`
- we are using `clusterScoped: true` option

**nats-cluster**
- image: `nats:2.1.9`
- we are creating ServiceAccounts for auth
- we are using config reloader
- the cluster size is 3

**nats-streaming**
- image: nats-streaming:0.19.0

I am unable to catch any logs related with errors or warns in nats-operator, nats-cluster and nats-streaming.

The deletion is being random - to restore proper config, I have to reload all affected NatsServiceRoles created for my services.
My services are using the following config for NetsServiceRole:

```
apiVersion: nats.io/v1alpha2
kind: NatsServiceRole
metadata:
  annotations:
    helm.fluxcd.io/antecedent: my-ns:helmrelease/company
  labels:
    nats_cluster: my-nats-cluster
  name: company
  namespace: my-nats-io
spec:
  permissions:
    publish:
    - '>'
    subscribe:
    - '>'
```

Moreover, the secrets for my services are being deleted, but for the nats-streaming, not.
Also configuration that is stored in nats-cluster secret (`nats.conf`) is not touched when bound tokens are deleted.
Please ping me back which information should I provide to create better description of the issue.

Thanks!
