### ISSUE TITLE
service?

### ISSUE THREAD

**Issue by k1ng440** [nats-io/nats-operator#49]
How to create a service?

```
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "cryptovalue-nats"
spec:
  size: 3
  version: "1.1.0"
```

**Comment by wallyqs** [comment]
Just apply via `kubectl` and then you would get a `cryptovalue-nats` service to which pods can connect (e.g. `nats.Connect("nats://cryptovalue-nats:4222")`)
```
echo '
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "cryptovalue-nats"
spec:
  size: 3
  version: "1.1.0"
' | kubectl apply -f -
```
