### ISSUE TITLE
Support installing the CRD from k8s manifests instead of from the operator

### ISSUE THREAD

**Issue by seriousben** [nats-io/nats-operator#81]
Instead of creating the CRDs from the code, I think it would make sense to create it from k8s manifests while installing the operator itself. This could be done for the helm chart or for all installs.

This would allow:
* using the `crd-install` helm hook in helm charts
* getting rid of a rule in Role definitions when using rbac required to install a CRD:
```
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
```

Implementation:
- support a command line flag to toggle crd install from the operator
- in the helm chart, disable crd installs from the operator
- in the helm chart, remove the rule for CRDs CRUD
