### ISSUE TITLE
Allow setting custom image for the NATS server

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats-operator#90]
Should allow making it possible to set a custom image for the server, for example:

```
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "example-nats-1"
spec:
  size: 3
  # version "1.3.0"
  image: "nats:1.3.0"
```
